src/Entity/Author.php
<?php

namespace App\Entity;

use App\Repository\AuthorRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AuthorRepository::class)]
class Author
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $username = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Book::class)]
    private Collection $bookList;

    #[ORM\Column]
    private ?int $nb_books = null;

    public function __construct()
    {
        $this->bookList = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return Collection<int, Book>
     */
    public function getBookList(): Collection
    {
        return $this->bookList;
    }

    public function addBookList(Book $bookList): static
    {
        if (!$this->bookList->contains($bookList)) {
            $this->bookList->add($bookList);
            $bookList->setAuthor($this);
        }

        return $this;
    }

    public function removeBookList(Book $bookList): static
    {
        if ($this->bookList->removeElement($bookList)) {
            // set the owning side to null (unless already changed)
            if ($bookList->getAuthor() === $this) {
                $bookList->setAuthor(null);
            }
        }

        return $this;
    }

    public function getNbBooks(): ?int
    {
        return $this->nb_books;
    }

    public function setNbBooks(int $nb_books): static
    {
        $this->nb_books = $nb_books;

        return $this;
    }

    public function __toString(): string
    {
        return $this->username;
    }

    public function addBook(Book $book)
    {
        $this->bookList->add($book);
    }
}

src/Form/AuthorType.php
<?php

namespace App\Form;

use App\Entity\Author;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AuthorType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('username')
            ->add('email')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Author::class,
        ]);
    }
}

src/Controller/AuthorController.php
<?php

namespace App\Controller;

use App\Entity\Author;
use App\Form\AuthorType;
use App\Repository\AuthorRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AuthorController extends AbstractController
{
    #[Route('/allAuthor', name: 'app_all_author')]
    public function showAll(AuthorRepository $authorRepo): Response
    {
        $authors = $authorRepo->findAll();
        return $this->render('author/index.html.twig', [
            'controller_name' => 'AuthorController',
            'authors' => $authors
        ]);
    }

    #[Route('/addAuthor', name: 'app_author_add')]
    public function addAuthor(ManagerRegistry $mr,Request $request): Response
    {
        $author = new Author();
        $form = $this->createForm(AuthorType::class, $author);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $mr->getManager();
            $em->persist($author);
            $em->flush();
            return $this->redirectToRoute('app_all_author');
        }

        return $this->render('author/add.html.twig', [
            'form' => $form->createView()
        ]);
    }

    #[Route('/editAuthor/{id}', name: 'app_author_edit')]
    public function editAuthor(ManagerRegistry $mr,Request $request,AuthorRepository $authorRepo, int $id): Response
    {
        $author = $authorRepo->find($id);
        $form = $this->createForm(AuthorType::class, $author);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $mr->getManager();
            $em->persist($author);
            $em->flush();
            return $this->redirectToRoute('app_all_author');
        }

        return $this->render('author/add.html.twig', [
            'form' => $form->createView()
        ]);
    }

    #[Route('/deleteAuthor/{id}', name: 'app_author_delete')]
    public function deleteAuthor(ManagerRegistry $mr,AuthorRepository $authorRepo, int $id): Response
    {
        $author = $authorRepo->find($id);
        $em = $mr->getManager();
        $em->remove($author);
        $em->flush();
        return $this->redirectToRoute('app_all_author');
    }

    #[Route('/listAuthorByEmail', name: 'app_author_listByEmail')]
    public function listAuthorByEmail(AuthorRepository $authorRepo): Response
    {
        $authors = $authorRepo->listAuthorByEmail();
        return $this->render('author/index.html.twig', [
            'controller_name' => 'AuthorController',
            'authors' => $authors
        ]);
    }

    //rechercher la liste des auteurs dont le nombre de livres est compris entre deux valeurs
    #[Route('/listAuthorByNbBook', name: 'app_author_listByNbBook')]
    public function listAuthorByNbBook(AuthorRepository $authorRepo,Request $request): Response
    {
        $min = $request->request->get('min');
        $max = $request->request->get('max');
        $authors = $authorRepo->listAuthorByNbBook($min, $max);
        return $this->render('author/index.html.twig', [
            'controller_name' => 'AuthorController',
            'authors' => $authors
        ]);
    }
}

templates/author/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AuthorController!{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    </style>

    <div class="example-wrapper">
        {{ form_start(form) }}
        {{ form_widget(form) }}
        <input type="submit" value="Save" />
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/author/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AuthorController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
        <form action="{{ path('app_author_listByNbBook') }}" method="post">
                <label for="min">min</label>
                <input type="number" name="min" id="min">
                <label for="max">max</label>
                <input type="number" name="max" id="max">
                <input type="submit" value="Search">
        </form>
        <table border="1">
                <tr>
                        <th>Username</th>
                        <th>Email</th>
                        <th>nbr_books</th>
                        <th>Actions</th>
                </tr>
                {% for author in authors %}
                <tr>
                        <td>{{ author.username }}</td>
                        <td>{{ author.email }}</td>
                        <td>{{ author.nbBooks }}</td>
                        <td><a href="{{ path('app_author_edit', {'id': author.id}) }}">edit</a>&nbsp;&nbsp;
                                <a href="{{ path('app_author_delete', {'id': author.id}) }}">delete</a></td>
                </tr>
                {% endfor %}

        </table>
</div>
{% endblock %}